INSERT INTO ACCOUNT (CURRENCY, MONEY, NAME, TREASURY) VALUES ('EUR', 5000.0, 'Andrew', TRUE);
INSERT INTO ACCOUNT (CURRENCY, MONEY, NAME, TREASURY) VALUES ('EUR', 15000.45, 'Karen', FALSE);
INSERT INTO ACCOUNT (CURRENCY, MONEY, NAME, TREASURY) VALUES ('EUR', 7500.23, 'Sarah', TRUE);